[package]
name = "melee-anal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
peppi = "2.0"
serde_json = "1.0.140"
soccer = "0.0.1"
dotenvy = "0.15"
