pub mod gamedata;
pub mod advanced;
pub mod analytics;
pub mod analysis_cache;
pub mod combat;
pub mod file_cache;
pub mod models;
pub mod punish;
// Table names mirror the real database schema, and the `gamePlayer` table is
// spelled that way on disk. The allow lives here rather than in `schema.rs`
// because that file is regenerated by the Diesel CLI.
#[allow(non_snake_case)]
pub mod schema;
pub mod stage_bounds;
pub mod testing;

// Re-export the embedded migrations bundle so callers outside of test code
// (e.g. the GUI app) can open a fresh DB at an arbitrary path and run all
// pending migrations without reaching into the `testing` module.
pub use self::testing::MIGRATIONS;



pub static NUM_STAGES: usize = 33;
pub static NUM_CHARACTERS: usize = 33;


pub mod db;
pub mod ingest;
pub mod replay;
pub mod stats;
pub mod store;
pub mod win_rates;

// The whole read/write API is re-exported flat, so callers say
// `stats_melee::player_summary` rather than naming the module it lives in.
// Which module a function sits in is an organizing detail, not part of the
// interface.
pub use self::db::{database_url, establish_connection, is_games_empty, open_database};
pub use self::ingest::{
    parse_new_replays, parse_new_replays_timed_at, parse_new_replays_with, IngestStrategy,
    IngestTimings,
};
pub use self::replay::{hash_slp_file, parse_replay_analysis, parse_single_replay};
pub use self::stats::*;
pub use self::store::*;
pub use self::win_rates::*;
